#!/bin/bash

echo "This command will commit all running containers"
echo "No tag will be assigned so they will be tagged 'latest'"

read -p "Are you sure you want to continue? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    for DOC in `~/bin/dnames` ;do echo $DOC; docker.io commit $DOC kartoza/$DOC; done
    docker.io images
fi


