#!/bin/bash

echo "This command will export all running containers"

read -p "Are you sure you want to continue? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    for DOC in `~/bin/docker-helpers/dnames`
    do 
      echo $DOC
      docker export $DOC > docker-export-${DOC}.tar
    done
    ls -lah docker-export*
fi


