#!/bin/bash

echo "This command will export all running containers"
echo "You can re-import these containers on another host using:"
echo "cat <exported_container>.tar | docker import - organisation/image:tag"

read -p "Are you sure you want to continue? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  for CONTAINER in `dnames`
  do
    NAME="docker-export-${CONTAINER}.tar"
    echo "Exporting${CONTAINER} to ${NAME}"
    docker export ${CONTAINER} > ${NAME}
  done
  ls -lah docker-export*
fi


