#!/bin/bash

# Extract docker passwords written to logs
# and write to a file called PASSWORDS.md

# Tim Sutton, May 2014

echo "# Docker Passwords"
for SITE in `dnames`
do 
  echo "## Site: $SITE"
  docker logs ${SITE} | grep password
  echo ""
done
