#!/bin/bash

# Extract docker passwords written to logs
# and write to a file called PASSWORDS.md

# Tim Sutton, May 2014

echo "# Docker Passwords" > PASSWORDS.md 
for SITE in `dnames`
do 
  echo "## Site: $SITE" >> PASSWORDS.md; docker.io logs ${SITE} | grep password >> PASSWORDS.md; echo "" >> PASSWORDS.md
done
cat PASSWORDS.md
