#!/bin/bash

echo "This command will remove all stopped docker containers."

read -p "Are you sure you want to continue? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker rm $(docker ps -a -q)
fi

docker ps -a
