#!/bin/bash

echo "This command will remove all untagged docker images."

read -p "Are you sure you want to continue? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker.io rmi $(docker.io images -a | grep "^<none>" | awk '{print $3}')
fi

docker.io images
